### ISSUE TITLE
Incorrect steps?

### ISSUE THREAD

**Issue by ford-at-aws** [awsdocs/aws-doc-sdk-examples-tools#61]
On [this section](https://github.com/awsdocs/aws-doc-sdk-examples-tools?tab=readme-ov-file#new-releases), I see there's an opening instruction to find the latest commit SHA and update https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/.github/workflows/validate-doc-metadata.yml to that tag. 

I don't think this correct to update `main` like that; you would update a branch, first, correct?

**Comment by DavidSouther** [comment]
You could also use the branch name, yes. This is only for testing, the update with the raw SHA never gets merged.

**Comment by ford-at-aws** [comment]
OK. As far as I can tell, this issue is nonsense. Closing.
