### ISSUE TITLE
Improve title/title_abbrev validation

### ISSUE THREAD

**Issue by DavidSouther** [awsdocs/aws-doc-sdk-examples-tools#96]
Basics scenarios have generated title/title_abbrev fields when they are left blank. This is for consistency across examples. However, it is allowed to add a custom value for these fields in the case when there are multiple Basics scenarios, such as for S3 we will likely have something like:

Learn the basics
Learn the basics of Directory Buckets

The validator should reject metadata that has a single Basics for a service if the metadata has these fields so it is only used for secondary scenarios.

Also warn when title/_abbrev are missing and would not be generated.

Internally: P154609845

**Comment by brmur** [comment]
This is being tracked internally. Closing.
